### ISSUE TITLE
'Account for imperfect detection' sometimes fails to generate graphs

### ISSUE THREAD

**Issue by DesiQuintans** [benflips/nCovForecast#1]
You should be able to replicate this by looking at the Singapore data and choosing _Account for imperfect detection: Yes_. It looks like any country with too few cases will return **Error: An error has occurred. Check your logs or contact the app author for clarification.**.

**Comment by benflips** [comment]
Thanks Desi,

That’s because there are insufficient data to estimate detection in those cases. The data will emerge over the next week or so. I should make the behaviour prettier in the meantime :-) will fix it up as soon as I get a chance.

B

Excuse the brevity: sent from my phone.

On 13 Mar 2020, at 10:38, Desi Quintans <notifications@github.com<mailto:notifications@github.com>> wrote:


You should be able to replicate this by looking at the Singapore data and choosing Account for imperfect detection: Yes. It looks like any country with too few cases will return Error: An error has occurred. Check your logs or contact the app author for clarification..

**Comment by benflips** [comment]
I've resolved this one simply by removing plotting of detection-corrected data.  It's just a translation of the y-axis at the moment, and doesn't really tell us anything more than the original plots.  Detection-corrected numbers are reported only in the sidebar table.
